"""Fix OTP relationship

Revision ID: 8cec8b301235
Revises: 3a910a4282a3
Create Date: 2026-01-29 02:04:58.675193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cec8b301235'
down_revision: Union[str, Sequence[str], None] = '3a910a4282a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'is_active')
    # ### end Alembic commands ###
